### ISSUE TITLE
/!\ Webhook harcodé dans le code

### ISSUE THREAD

**Issue by d0p1s4m4** [elio-centrique/WakStuff#1]
https://github.com/elio-centrique/WakStuff/blob/e3f16bb6afecb55c067d81e02663589d1d9c7d68/bot.rb#L12
Le webhook est accessible à la vue de tous sur github et donc n'importe qui peut l'utiliser pour poster n'importe quoi sur ton salon. 
Une solution à ce problème serait de la déplacer dans un fichier de configuration externe et invalider celui actuel.

**Comment by elio-centrique** [comment]
pour l'instant le webhook n'est pas vraiment utilisé, mais oui c'est effectivement un problème de sécurité, merci pour l'info !

**Comment by elio-centrique** [comment]
Problème réglé
